# Generated by Django 4.0.4 on 2022-07-29 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('faculty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adhar_no', models.CharField(max_length=100, unique=True)),
                ('faculty_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('faculty_image', models.ImageField(default='', upload_to='faculty/images')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title_of_event', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('enclosure_no', models.IntegerField(unique=True)),
                ('attended', models.CharField(default='[]', max_length=10000)),
                ('organised', models.CharField(default='[]', max_length=10000)),
                ('category', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('duration', models.DateTimeField()),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OutreachActivity',
            fields=[
                ('enclosure_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('organisation', models.CharField(max_length=100)),
                ('nameOfActivity', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyOutreachActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.contactdetails')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.outreachactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.event')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.contactdetails')),
            ],
        ),
    ]
