# Generated by Django 4.0.4 on 2022-08-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='faculty_name',
        ),
    ]
