# Generated by Django 4.0.4 on 2022-07-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0002_alter_contactdetails_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='user',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
