# Generated by Django 4.0.4 on 2022-08-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
