# Generated by Django 4.0.4 on 2022-08-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentclassroom_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
