# Generated by Django 4.0.4 on 2022-08-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_name_student_last_name_student_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
