# Generated by Django 4.0.4 on 2022-07-30 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScience',
            fields=[
                ('primary_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], max_length=50, verbose_name='status')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date(2022, 7, 30))),
            ],
        ),
    ]
