# Generated by Django 4.0.4 on 2022-07-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('student', '0001_initial'),
        ('attendance', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.subject'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.contactdetails'),
        ),
    ]
