# Generated by Django 4.0.4 on 2022-07-29 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_mcq_question_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='primary_key',
            field=models.CharField(default=datetime.datetime(2022, 7, 30, 5, 26, 21, 330153), max_length=10, primary_key=True, serialize=False),
        ),
    ]
