# Generated by Django 4.0.4 on 2022-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='department',
        ),
    ]
